name: ROS 2 CI
on:
  push:
jobs:
  build:
    name: Build ROS2 workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          path: .

      - name: Install Cap'n Proto 0.7.0
        run: |
          sudo apt-get update
          sudo apt install build-essential autoconf automake libtool
          wget https://github.com/capnproto/capnproto/archive/v0.7.0.tar.gz
          tar xvzf v0.7.0.tar.gz
          cd capnproto-0.7.0/c++
          autoreconf -i
          ./configure
          make -j6
          sudo make install

      - name: Setup ROS2 workspace
        uses: ichiro-its/ros2-ws-action/setup@v1.0.1
        with:
          distro: humble

      - name: Build ROS2 workspace
        uses: ichiro-its/ros2-ws-action/build@v1.0.1
        with:
          distro: humble